### ISSUE TITLE
Regarding the YouTube Pose Subset dataset

### ISSUE THREAD

**Issue by Swetha5** [jjcharles/personalizedpose#1]
@jjcharles : In the paper, you have defined 'YouTube Pose Subset' dataset which is a five video subset from YouTube Pose. But, the details of split are not provided. It would be helpful if you can share the details regarding the subset split.

TIA.

**Comment by jjcharles** [comment]
Please download the updated dataset from: https://www.robots.ox.ac.uk/~vgg/data/pose/download/YouTube_Pose_dataset_1.0.zip

The MATLAB data structure contains a field called 'isYouTubePoseSubset' which indicates which video belongs to the YouTube Pose Subset dataset.

**Comment by Swetha5** [comment]
@jjcharles  Thanks a lot!
